version: 0.2

phases:
  installs:
    runtime-version:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 872924916506.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=872924916506.dkr.ecr.us-east-1.amazonaws.com/chunithm-log:latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker-compose up -d
      - docker tag chunithm-log-web:latest $REPOSITORY_URI
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI
      # - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > artifact.json
      - cat artifact.json 
artifacts:
    files: artifact.json