version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 5480:5480

  web:
    image: chunithm-log-web
    build: 
      context: ./nextjs
    ports:
      - '4100:4100'

  datascraper :
    image: chunithm-log-datascraper
    build: 
      context: ./scrapper

volumes:
  data:
      