version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - chinilog
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 5480:8080
    networks:
      - chinilog

  web:
    image: chunithm-log-web
    build: 
      context: ./nextjs
    ports:
      - '4100:4100'
    networks:
      - chinilog

  datascraper :
    image: chunithm-log-datascraper
    build: 
      context: ./scrapper
    networks:
      - chinilog


networks:
  chinilog:
    driver: bridge


volumes:
  data:
      